[package]
name = "publicflow"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.3"
petgraph = "0.6.0"
yaml-rust = "0.4.5"
linked-hash-map = "0.5.3"
ggez = "0.7"
