- city: PlayCity
  id: 0
  lat: 11.05
  lon: 48.05
  name: Zero
- city: PlayCity
  id: 1
  lat: 11.10
  lon: 48.10
  name: One
- city: PlayCity
  id: 10
  lat: 11.075
  lon: 48.075
  name: Ten
- city: PlayCity
  id: 100
  lat: 11.025
  lon: 48.025
  name: Hundred
- city: PlayCity
  id: 1000
  lat: 11.00
  lon: 48.00
  name: Thousand  
- city: PlayCity
  id: 2
  lat: 11.10
  lon: 48.00
  name: Two
- city: PlayCity
  id: 20
  lat: 11.075
  lon: 48.025
  name: Twenty
- city: PlayCity
  id: 200
  lat: 11.025
  lon: 48.075
  name: Twohundred
- city: PlayCity
  id: 2000
  lat: 11.00
  lon: 48.10
  name: Twothousand
- city: PlayCity
  id: 3
  lat: 11.05
  lon: 48.00
  name: Three
- city: PlayCity
  id: 300
  lat: 11.05
  lon: 48.075
  name: Threehundred
- city: PlayCity
  id: 3000
  lat: 11.05
  lon: 48.10
  name: Threethousand