visual:
  screen_size: 
    x: 1920.0
    y: 1150.0
  latitude:
    min: 11.4606
    max: 11.7036
  longitude:
    min: 48.0416
    max: 48.2649
  screen_offset: 100.0
  radius_station: 10.0
  radius_pod: 5.0
  width_line: 2.0
  desired_fps: 20 # TODO: decouple game speed from draw rate
  vsync: true
logic:
  number_of_people: 1000
  pod_capacity: 20
  transition_time: 30
  pod_spawn_rate: 30 # every so many seconds a pod should be spawned till enough are there
