general:
  environment: gather # used for data gathering subfolder
  town: "benjamintown"
  mode: "visual" # "visual" | "headless" # this is not implemented since it would require a lot of extra work right now 
  override: true # if false everything has to be set in the config of the town
  command_on_start: "run config/benjamintown/scripts/benchmark.pf"
  # command_on_start: "sleep 1 sim"
visual:
  vsync: true
logic:
  number_of_people: 5000
  pod_capacity: 300
  line_pods_per_hour: 6
  station_pods_per_hour: 60 # TODO: use this as a hard limit for the stations
  speed_multiplier: 50
  transition_time: 60
  pod_in_station_seconds: 40
  shuffle_people: true
  use_earth_coordinates: false
  distance_factor: 1000
