visual:
  screen_size: 
    x: 1920.0
    y: 1150.0
  latitude:
    min: 00.00
    max: 11.00
  longitude:
    min: 00.00
    max: 11.00
  screen_offset: 100.0
  radius_station: 10.0
  radius_pod: 5.0
  width_line: 2.0
