- city: München
  id: 0
  lat: 11.5654
  lon: 48.1394
  name: Karlsplatz (Stachus)
- city: München
  id: 1
  lat: 11.5777
  lon: 48.1364
  name: Marienplatz
- city: München
  id: 2
  lat: 11.5828
  lon: 48.1339
  name: Isartor
- city: München
  id: 3
  lat: 11.5939
  lon: 48.1286
  name: Rosenheimer Platz
- city: München
  id: 4
  lat: 11.6041
  lon: 48.1281
  name: Ostbahnhof
- city: München
  id: 5
  lat: 11.5611
  lon: 48.1403
  name: Hauptbahnhof
- city: München
  id: 6
  lat: 11.5488
  lon: 48.1435
  name: Hackerbrücke
- city: München
  id: 9
  lat: 11.4606
  lon: 48.1488
  name: Pasing
- city: München
  id: 10
  lat: 11.5474
  lon: 48.1595
  name: Leonrodplatz
- city: München
  id: 17
  lat: 11.5881
  lon: 48.1376
  name: Maxmonument
- city: München
  id: 19
  lat: 11.5753
  lon: 48.1395
  name: Theatinerstraße
- city: München
  id: 20
  lat: 11.596
  lon: 48.1361
  name: Maximilianeum
- city: München
  id: 27
  lat: 11.5496
  lon: 48.1251
  name: Poccistraße
- city: München
  id: 29
  lat: 11.5533
  lon: 48.1554
  name: Hochschule München
- city: München
  id: 34
  lat: 11.5584
  lon: 48.1295
  name: Goetheplatz
- city: München
  id: 36
  lat: 11.5811
  lon: 48.1244
  name: Mariahilfplatz
- city: München
  id: 37
  lat: 11.575
  lon: 48.1603
  name: Kurfürstenplatz
- city: München
  id: 44
  lat: 11.5664
  lon: 48.1333
  name: Sendlinger Tor
- city: München
  id: 46
  lat: 11.5696
  lon: 48.1454
  name: Karolinenplatz
- city: München
  id: 48
  lat: 11.5359
  lon: 48.1463
  name: Donnersbergerstraße
- city: München
  id: 54
  lat: 11.5777
  lon: 48.1429
  name: Odeonsplatz
- city: München
  id: 59
  lat: 11.5344
  lon: 48.14
  name: Trappentreustraße
- city: München
  id: 64
  lat: 11.5805
  lon: 48.149
  name: Universität
- city: München
  id: 65
  lat: 11.5916
  lon: 48.1328
  name: Am Gasteig
- city: München
  id: 74
  lat: 11.5849
  lon: 48.1571
  name: Giselastraße
- city: München
  id: 101
  lat: 11.564
  lon: 48.1462
  name: Königsplatz
- city: München
  id: 111
  lat: 11.5643
  lon: 48.1512
  name: Theresienstraße
- city: München
  id: 121
  lat: 11.5663
  lon: 48.1548
  name: Josephsplatz
- city: München
  id: 131
  lat: 11.568
  lon: 48.1612
  name: Hohenzollernplatz
- city: München
  id: 138
  lat: 11.5762
  lon: 48.1279
  name: Fraunhoferstraße
- city: München
  id: 146
  lat: 11.5765
  lon: 48.1191
  name: Kolumbusplatz
- city: München
  id: 153
  lat: 11.5588
  lon: 48.1471
  name: Stiglmaierplatz
- city: München
  id: 154
  lat: 11.5446
  lon: 48.1503
  name: Maillingerstraße
- city: München
  id: 156
  lat: 11.5335
  lon: 48.153
  name: Rotkreuzplatz
- city: München
  id: 158
  lat: 11.5284
  lon: 48.1693
  name: Westfriedhof
- city: München
  id: 167
  lat: 11.4932
  lon: 48.1656
  name: Amalienburgstraße
- city: München
  id: 172
  lat: 11.5116
  lon: 48.1556
  name: Romanplatz
- city: München
  id: 197
  lat: 11.5522
  lon: 48.1357
  name: Theresienwiese
- city: München
  id: 198
  lat: 11.5397
  lon: 48.1335
  name: Schwanthalerhöhe
- city: München
  id: 200
  lat: 11.5227
  lon: 48.1344
  name: Westendstraße
- city: München
  id: 201
  lat: 11.5114
  lon: 48.1351
  name: Friedenheimer Straße
- city: München
  id: 202
  lat: 11.503
  lon: 48.1355
  name: Laimer Platz
- city: München
  id: 212
  lat: 11.5074
  lon: 48.1804
  name: Moosach
- city: München
  id: 225
  lat: 11.5291
  lon: 48.1764
  name: Georg-Brauchle-Ring
- city: München
  id: 231
  lat: 11.5403
  lon: 48.2139
  name: Feldmoching
- city: München
  id: 249
  lat: 11.5666
  lon: 48.1755
  name: Petuelring
- city: München
  id: 258
  lat: 11.5567
  lon: 48.1787
  name: Olympiazentrum
- city: München
  id: 268
  lat: 11.5295
  lon: 48.182
  name: Olympia-Einkaufszentrum
- city: München
  id: 274
  lat: 11.5173
  lon: 48.1818
  name: Moosacher St.-Martins-Platz
- city: München
  id: 277
  lat: 11.5457
  lon: 48.1862
  name: Oberwiesenfeld
- city: München
  id: 287
  lat: 11.5727
  lon: 48.1715
  name: Scheidplatz
- city: München
  id: 297
  lat: 11.5785
  lon: 48.1669
  name: Bonner Platz
- city: München
  id: 305
  lat: 11.6145
  lon: 48.1924
  name: Freimann
- city: München
  id: 318
  lat: 11.6125
  lon: 48.2027
  name: Kieferngarten
- city: München
  id: 321
  lat: 11.5859
  lon: 48.1711
  name: Parzivalplatz
- city: München
  id: 322
  lat: 11.5862
  lon: 48.1673
  name: Potsdamer Straße
- city: München
  id: 346
  lat: 11.5864
  lon: 48.1727
  name: Schwabinger Tor
- city: Garching (b München)
  id: 347
  lat: 11.6712
  lon: 48.2649
  name: Garching-Forschungszentrum
- city: München
  id: 351
  lat: 11.6166
  lon: 48.2116
  name: Fröttmaning
- city: Garching (b München)
  id: 352
  lat: 11.6308
  lon: 48.2472
  name: Garching-Hochbrück
- city: Garching (b München)
  id: 353
  lat: 11.6525
  lon: 48.2494
  name: Garching
- city: München
  id: 354
  lat: 11.5863
  lon: 48.1619
  name: Münchner Freiheit
- city: München
  id: 355
  lat: 11.5883
  lon: 48.1761
  name: Am Münchner Tor
- city: München
  id: 356
  lat: 11.5904
  lon: 48.1842
  name: Domagkstraße
- city: München
  id: 357
  lat: 11.5912
  lon: 48.1875
  name: Schwabing Nord
- city: München
  id: 358
  lat: 11.5903
  lon: 48.1666
  name: Dietlindenstraße
- city: München
  id: 363
  lat: 11.5974
  lon: 48.1734
  name: Nordfriedhof
- city: München
  id: 364
  lat: 11.6039
  lon: 48.1795
  name: Alte Heide
- city: München
  id: 365
  lat: 11.608
  lon: 48.1833
  name: Studentenstadt
- city: München
  id: 382
  lat: 11.6154
  lon: 48.1429
  name: Böhmerwaldplatz
- city: München
  id: 383
  lat: 11.607
  lon: 48.1393
  name: Prinzregentenplatz
- city: München
  id: 384
  lat: 11.5979
  lon: 48.1357
  name: Max-Weber-Platz
- city: München
  id: 386
  lat: 11.5886
  lon: 48.1396
  name: Lehel
- city: München
  id: 388
  lat: 11.6305
  lon: 48.176
  name: St. Emmeram
- city: München
  id: 434
  lat: 11.6136
  lon: 48.1522
  name: Effnerplatz
- city: München
  id: 439
  lat: 11.6232
  lon: 48.1537
  name: Arabellapark/Klinikum Bogenhausen
- city: München
  id: 444
  lat: 11.6204
  lon: 48.1533
  name: Arabellapark
- city: München
  id: 446
  lat: 11.6163
  lon: 48.1489
  name: Richard-Strauss-Straße
- city: München
  id: 463
  lat: 11.5731
  lon: 48.1812
  name: Milbertshofen
- city: München
  id: 465
  lat: 11.5727
  lon: 48.1875
  name: Frankfurter Ring
- city: München
  id: 474
  lat: 11.5718
  lon: 48.197
  name: Am Hart
- city: München
  id: 479
  lat: 11.5682
  lon: 48.2049
  name: Harthof
- city: München
  id: 481
  lat: 11.5625
  lon: 48.2128
  name: Dülferstraße
- city: München
  id: 483
  lat: 11.5563
  lon: 48.2132
  name: Hasenbergl
- city: München
  id: 519
  lat: 11.6421
  lon: 48.1218
  name: St.-Veit-Straße
- city: München
  id: 523
  lat: 11.6337
  lon: 48.1361
  name: Berg am Laim
- city: München
  id: 531
  lat: 11.6633
  lon: 48.1255
  name: Trudering
- city: München
  id: 591
  lat: 11.5892
  lon: 48.1798
  name: Anni-Albers-Straße
- city: München
  id: 593
  lat: 11.529
  lon: 48.1635
  name: Gern
- city: München
  id: 611
  lat: 11.6444
  lon: 48.0895
  name: Neuperlach Süd
- city: München
  id: 621
  lat: 11.6433
  lon: 48.0954
  name: Therese-Giehse-Allee
- city: München
  id: 631
  lat: 11.6474
  lon: 48.101
  name: Neuperlach Zentrum
- city: München
  id: 641
  lat: 11.6464
  lon: 48.1091
  name: Quiddestraße
- city: München
  id: 650
  lat: 11.6306
  lon: 48.1188
  name: Michaelibad
- city: München
  id: 658
  lat: 11.6191
  lon: 48.1204
  name: Innsbrucker Ring
- city: München
  id: 662
  lat: 11.6095
  lon: 48.1185
  name: Karl-Preis-Platz
- city: München
  id: 668
  lat: 11.5836
  lon: 48.1191
  name: Ostfriedhof
- city: München
  id: 672
  lat: 11.5971
  lon: 48.1029
  name: Schwanseestraße
- city: München
  id: 673
  lat: 11.5946
  lon: 48.1108
  name: Giesing
- city: München
  id: 685
  lat: 11.5502
  lon: 48.0767
  name: Großhesseloher Brücke
- city: München
  id: 689
  lat: 11.5362
  lon: 48.1169
  name: Harras
- city: München
  id: 695
  lat: 11.5483
  lon: 48.1193
  name: Implerstraße
- city: München
  id: 704
  lat: 11.5335
  lon: 48.1334
  name: Heimeranplatz
- city: München
  id: 712
  lat: 11.5871
  lon: 48.1128
  name: Untersbergstraße
- city: München
  id: 722
  lat: 11.5795
  lon: 48.1152
  name: Silberhornstraße
- city: München
  id: 731
  lat: 11.5698
  lon: 48.1115
  name: Candidplatz
- city: München
  id: 740
  lat: 11.5747
  lon: 48.1092
  name: Wettersteinplatz
- city: München
  id: 742
  lat: 11.5818
  lon: 48.104
  name: St.-Quirin-Platz
- city: München
  id: 744
  lat: 11.5184
  lon: 48.1401
  name: Lautensackstraße
- city: München
  id: 750
  lat: 11.581
  lon: 48.0979
  name: Mangfallplatz
- city: München
  id: 759
  lat: 11.6344
  lon: 48.127
  name: Josephsburg
- city: München
  id: 763
  lat: 11.6447
  lon: 48.1259
  name: Kreillerstraße
- city: München
  id: 767
  lat: 11.6707
  lon: 48.1305
  name: Moosfeld
- city: München
  id: 768
  lat: 11.6898
  lon: 48.1334
  name: Messestadt West
- city: München
  id: 770
  lat: 11.7036
  lon: 48.1334
  name: Messestadt Ost
- city: München
  id: 800
  lat: 11.5266
  lon: 48.1165
  name: Partnachplatz
- city: München
  id: 810
  lat: 11.5171
  lon: 48.1179
  name: Westpark
- city: München
  id: 849
  lat: 11.5487
  lon: 48.1122
  name: Brudermühlstraße
- city: München
  id: 856
  lat: 11.5466
  lon: 48.1014
  name: Thalkirchen (Tierpark)
- city: München
  id: 862
  lat: 11.538
  lon: 48.0984
  name: Obersendling
- city: München
  id: 865
  lat: 11.5241
  lon: 48.0979
  name: Aidenbachstraße
- city: München
  id: 869
  lat: 11.5135
  lon: 48.0981
  name: Machtlfinger Straße
- city: München
  id: 873
  lat: 11.4985
  lon: 48.0947
  name: Forstenrieder Allee
- city: München
  id: 874
  lat: 11.4903
  lon: 48.0905
  name: Basler Straße
- city: München
  id: 875
  lat: 11.4804
  lon: 48.0886
  name: Fürstenried West
- city: München
  id: 877
  lat: 11.5024
  lon: 48.1163
  name: Holzapfelkreuth
- city: München
  id: 881
  lat: 11.4901
  lon: 48.1184
  name: Haderner Stern
- city: München
  id: 886
  lat: 11.4772
  lon: 48.1155
  name: Großhadern
- city: München
  id: 895
  lat: 11.4738
  lon: 48.1089
  name: Klinikum Großhadern
- city: München
  id: 903
  lat: 11.49
  lon: 48.1246
  name: Gondrellplatz
- city: München
  id: 908
  lat: 11.5031
  lon: 48.1397
  name: Fürstenrieder Straße
- city: München
  id: 911
  lat: 11.4888
  lon: 48.1409
  name: Willibaldplatz
- city: Grünwald (Kr München)
  id: 1153
  lat: 11.5236
  lon: 48.0416
  name: Derbolfinger Platz
- city: München
  id: 1166
  lat: 11.5592
  lon: 48.1393
  name: Hauptbahnhof Süd
- city: München
  id: 1167
  lat: 11.5608
  lon: 48.1412
  name: Hauptbahnhof Nord
