general:
  environment: route # used for data gathering subfolder
  town: "benjamintown"
  mode: "visual" # "visual" | "headless" # this is not implemented since it would require a lot of extra work right now 
  override: true # if false everything has to be set in the config of the town
  command_on_start: "run config/benjamintown/spawn_pods_conc.pf"
  # command_on_start: "sleep 1 sim"
visual:
  vsync: true
logic:
  use_earth_coordinates: false
  distance_factor: 1000
  number_of_people: 1
  pod_capacity: 50
  line_pods_per_hour: 12
  station_pods_per_hour: 40 # TODO: use this as a hard limit for the stations
  speed_multiplier: 50
  transition_time: 30
  pod_in_station_seconds: 30
  shuffle_people: true
