general:
  town: "benchmark"
  override: true
  # command_on_start: "run scripts/spawn_pods_playground_v3.pf"
  command_on_start: "run scripts/spawn_pods_benjamintown.pf"
  # command_on_start: "sleep $(3600 / $config.logic.pods_per_hour) sim"
visual:
  screen_size: 
    x: 1920.0
    y: 1150.0
  # latitude:
  #   min: 11.00
  #   max: 11.10
  # longitude:
  #   min: 48.00
  #   max: 48.10
  screen_offset: 100.0
  radius_station: 10.0
  radius_pod: 5.0
  width_line: 2.0
  desired_fps: 100 # TODO: decouple game speed from draw rate
  vsync: true
logic:
  number_of_people: 1000
  pod_capacity: 20
  transition_time: 30
  pod_in_station_seconds: 30
  pods_per_hour: 50
  shuffle_people: true

