network:
  STATIONS_PATH: "./config/playground/stations_in_lines.yaml"
  ALL_LINES_PATH: "./config/playground/all_lines.yaml"
  # SUBWAY_LINES_PATH: "./config/subway_lines.yaml"
  # TRAM_LINES_PATH: "./config/tram_lines.yaml"
visual:
  SCREEN_SIZE: 
    X: 1920.0
    Y: 1150.0
  LATITUDE:
    MIN: 11.00
    MAX: 11.10
  LONGITUDE:
    MIN: 48.00
    MAX: 48.10
  SCREEN_OFFSET: 100.0
  RADIUS_STATION: 10.0
  RADIUS_POD: 5.0
  WIDTH_LINE: 2.0
  DESIRED_FPS: 20 # TODO: decouple game speed from draw rate
  VSYNC: true
logic:
  NUMBER_OF_PEOPLE: 300
  POD_CAPACITY: 5
  TRANSITION_TIME: 30
  POD_SPAWN_RATE: 30 # every so many seconds a pod should be spawned till enough are there
