general:
  environment: dev # used for data gathering subfolder
  town: "benchmark"
  mode: "visual" # "visual" | "headless" # this is not implemented since it would require a lot of extra work right now 
  override: true # if false everything has to be set in the config of the town
  # command_on_start: "run scripts/spawn_pods_playground_v3.pf"
  # command_on_start: "run scripts/spawn_pods_benjamintown.pf"
  command_on_start: "run config/benchmark/spawn_pods_benjamintown.pf"
  # command_on_start: "sleep $(3600 / $config.logic.pods_per_hour) sim"
visual:
  vsync: true
logic:
  speed_multiplier: 200
  number_of_people: 1000
  pod_capacity: 20
  transition_time: 30
  pod_in_station_seconds: 30
  pods_per_hour: 60
  shuffle_people: true

