general:
  town: "playground"
  override: true
visual:
  screen_size: 
    x: 1920.0
    y: 1150.0
  latitude:
    min: 11.00
    max: 11.10
  longitude:
    min: 48.00
    max: 48.10
  screen_offset: 100.0
  radius_station: 10.0
  radius_pod: 5.0
  width_line: 2.0
  desired_fps: 20 # TODO: decouple game speed from draw rate
  vsync: true
logic:
  number_of_people: 100
  pod_capacity: 5
  transition_time: 30
  pods_per_hour: 60 # TODO: so many pods can arrive per hour at a station 

