- city: München
  id: 231
  lat: 11.5403
  lon: 48.2139
  name: Feldmoching
- city: München
  id: 212
  lat: 11.5074
  lon: 48.1804
  name: Moosach
- city: München
  id: 202
  lat: 11.503
  lon: 48.1355
  name: Laimer Platz
- city: München
  id: 870
  lat: 11.4738
  lon: 48.1089
  name: Klinikum Großhadern
- city: München
  id: 875
  lat: 11.4804
  lon: 48.0886
  name: Fürstenried West
- city: München
  id: 268
  lat: 11.5295
  lon: 48.182
  name: Olympia-Einkaufszentrum
- city: München
  id: 158
  lat: 11.5284
  lon: 48.1693
  name: Westfriedhof
- city: München
  id: 200
  lat: 11.5227
  lon: 48.1344
  name: Westendstraße
- city: München
  id: 474
  lat: 11.5718
  lon: 48.197
  name: Am Hart
- city: München
  id: 258
  lat: 11.5567
  lon: 48.1787
  name: Olympiazentrum
- city: München
  id: 287
  lat: 11.5727
  lon: 48.1715
  name: Scheidplatz
- city: München
  id: 5
  lat: 11.5611
  lon: 48.1403
  name: Hauptbahnhof
- city: München
  id: 695
  lat: 11.5483
  lon: 48.1193
  name: Implerstraße
- city: München
  id: 44
  lat: 11.5664
  lon: 48.1333
  name: Sendlinger Tor
- city: München
  id: 354
  lat: 11.5863
  lon: 48.1619
  name: Münchner Freiheit
- city: München
  id: 54
  lat: 11.5777
  lon: 48.1429
  name: Odeonsplatz
- city: München
  id: 384
  lat: 11.5979
  lon: 48.1357
  name: Max-Weber-Platz
- city: München
  id: 145
  lat: 11.5765
  lon: 48.1191
  name: Kolumbusplatz
- city: München
  id: 351
  lat: 11.6166
  lon: 48.2116
  name: Fröttmaning
- city: München
  id: 439
  lat: 11.6204
  lon: 48.1533
  name: Arabellapark
- city: München
  id: 658
  lat: 11.6191
  lon: 48.1204
  name: Innsbrucker Ring
- city: München
  id: 750
  lat: 11.581
  lon: 48.0979
  name: Mangfallplatz
- city: München
  id: 631
  lat: 11.6474
  lon: 48.101
  name: Neuperlach Zentrum
- city: München
  id: 770
  lat: 11.7036
  lon: 48.1334
  name: Messestadt Ost
- city: München
  id: 611
  lat: 11.6444
  lon: 48.0895
  name: Neuperlach Süd