# TODO: implement connections to clearly define time between stations
# TODO: implement a way to assign pods to lines
network:
  n_stations: 26 # could also be infered
  station_coordinates:
    FeldM: 
      id: 0
      coords: {x: 0, y: 0}
    Moos:
      id: 1
      coords: {x: 0, y: 10}
    LaimerP:
      id: 2
      coords: {x: 0, y: 20}
    KlGrossH:
      id: 3
      coords: {x: 0, y: 30}
    FürstW:
      id: 4
      coords: {x: 0, y: 40}
    OEZ:
      id: 5
      coords: {x: 10, y: 10}
    WestFH:
      id: 6
      coords: {x: 10, y: 15}
    WEStr:
      id: 7
      coords: {x: 10, y: 20}
    Hart:
      id: 8
      coords: {x: 20, y: 0}
    OZ:
      id: 9
      coords: {x: 20, y: 10}
    ScheidP:
      id: 10
      coords: {x: 30, y: 10}
    HBF:
      id: 11
      coords: {x: 30, y: 20}
    Impler:
      id: 12
      coords: {x: 30, y: 35}
    SendlT:
      id: 13
      coords: {x: 35, y: 27}
    MucFr:
      id: 14
      coords: {x: 40, y: 10}
    OdeonsP:
      id: 15
      coords: {x: 40, y: 20}
    MaxWebP:
      id: 16
      coords: {x: 50, y: 20}
    KolumbP:
      id: 17
      coords: {x: 50, y: 30}
    Froettm:
      id: 18
      coords: {x: 60, y: 0}
    ArabP:
      id: 19
      coords: {x: 60, y: 10}
    InnsbR:
      id: 20
      coords: {x: 60, y: 20}
    MangfP:
      id: 21
      coords: {x: 60, y: 30}
    NPerlZ:
      id: 22
      coords: {x: 65, y: 25}
    GarchFZ:
      id: 23
      coords: {x: 70, y: 0}
    MesseOst:
      id: 24
      coords: {x: 70, y: 20}
    NPerlS:
      id: 25
      coords: {x: 70, y: 25}
  lines: 
    - name: u1
      stations: [5,6,11,13,17,21]
      # distance: [1,2,1,3,3] // one shorter than stations or same length if circular // TODO: implement 
      circular: false
    - name: u2
      stations: [0,8,10,11,13,17,20,24]
      circular: false
    - name: u3
      stations: [1,5,9,10,14,15,13,12,4]
      circular: false
    - name: u4
      stations: [7,11,15,16,19]
      circular: false
    - name: u5
      stations: [2,7,11,15,16,20,22,25]
      circular: false
    - name: u6
      stations: [3,12,13,15,14,18,23]
      circular: false
    - name: u7
      stations: [5,6,11,13,17,20,22]
      circular: false
    - name: u8
      stations: [9,10,11,13,17,20,22]
      circular: false
  pods:
    n_pods: 57 # one per station per line | could be infered if n_pods == sum(len(line.stations))
people:
  n_people: 1000

