# TODO: implement connections to clearly define time between stations
# TODO: implement a way to assign pods to lines
# TODO: implement bus / sbahn / tram lines
# TODO: add and implement non node stations
network:
  n_stations: 26 # could also be infered
  station_coordinates:
    FeldM: 
      id: 0
      is_node: true
      can_spawn: true
      coords: {x: 0, y: 0}
    Moos:
      id: 1
      is_node: true
      can_spawn: true
      coords: {x: 0, y: 10}
    LaimerP:
      id: 2
      is_node: true
      can_spawn: true
      coords: {x: 0, y: 20}
    KlGrossH:
      id: 3
      is_node: true
      can_spawn: true
      coords: {x: 0, y: 30}
    FürstW:
      id: 4
      is_node: true
      can_spawn: true
      coords: {x: 0, y: 40}
    OEZ:
      id: 5
      is_node: true
      can_spawn: true
      coords: {x: 10, y: 10}
    WestFH:
      id: 6
      is_node: true
      can_spawn: false
      coords: {x: 10, y: 15}
    WEStr:
      id: 7
      is_node: true
      can_spawn: true
      coords: {x: 10, y: 20}
    AmHart:
      id: 8
      is_node: true
      can_spawn: false
      coords: {x: 20, y: 0}
    OZ:
      id: 9
      is_node: true
      can_spawn: true
      coords: {x: 20, y: 10}
    ScheidP:
      id: 10
      is_node: true
      can_spawn: false
      coords: {x: 30, y: 10}
    HBF:
      id: 11
      is_node: true
      can_spawn: false
      coords: {x: 30, y: 20}
    Impler:
      id: 12
      is_node: true
      can_spawn: false
      coords: {x: 30, y: 35}
    SendlT:
      id: 13
      is_node: true
      can_spawn: false
      coords: {x: 35, y: 27}
    MucFr:
      id: 14
      is_node: true
      can_spawn: false
      coords: {x: 40, y: 10}
    OdeonsP:
      id: 15
      is_node: true
      can_spawn: false
      coords: {x: 40, y: 20}
    MaxWebP:
      id: 16
      is_node: true
      can_spawn: false
      coords: {x: 50, y: 20}
    KolumbP:
      id: 17
      is_node: true
      can_spawn: false
      coords: {x: 50, y: 30}
    Froettm:
      id: 18
      is_node: true
      can_spawn: false
      coords: {x: 60, y: 0}
    ArabP:
      id: 19
      is_node: true
      can_spawn: true
      coords: {x: 60, y: 10}
    InnsbR:
      id: 20
      is_node: true
      can_spawn: false
      coords: {x: 60, y: 20}
    MangfP:
      id: 21
      is_node: true
      can_spawn: true
      coords: {x: 60, y: 30}
    NPerlZ:
      id: 22
      is_node: true
      can_spawn: true
      coords: {x: 65, y: 25}
    GarchFZ:
      id: 23
      is_node: true
      can_spawn: true
      coords: {x: 70, y: 0}
    MesseOst:
      id: 24
      is_node: true
      can_spawn: true
      coords: {x: 70, y: 20}
    NPerlS:
      id: 25
      is_node: true
      can_spawn: true
      coords: {x: 70, y: 25}
  lines: 
    - name: u1
      stations: [5,6,11,13,17,21]
      distances: [1413, 4888, 905, 1862, 3098] 
      circular: false
    - name: u2
      stations: [0,8,10,11,13,17,20,24]
      distances: [3770, 2762, 3685, 905, 1862, 4066, 7328]
      circular: false
    - name: u3
      stations: [1,5,9,10,14,15,13,12,4]
      distances: [1677, 2509, 1476, 1835, 2111, 1594, 2144, 6784]
      circular: false
    - name: u4
      stations: [7,11,15,16,19]
      distances: [3115, 1332, 1861, 2937]
      circular: false
    - name: u5
      stations: [2,7,11,15,16,20,22,25]
      distances: [1461, 3115, 1332, 1861, 2682, 3468, 1486]
      circular: false
    - name: u6
      stations: [3,12,13,15,14,18,23]
      distances: [6795, 2144, 1524, 2111, 6273, 8595]
      circular: false
    - name: u7
      # Olympia-Einkaufszentrum – Westfriedhof – Hauptbahnhof – Sendlinger Tor – Kolumbusplatz – Innsbrucker Ring – Neuperlach Zentrum
      stations: [5,6,11,13,17,20,22]
      distances: [1413, 4888, 905, 1862, 4066, 3468]
      circular: false
    - name: u8
      stations: [9,10,11,13,17,20,22]
      distances: [1476, 3685, 905, 1862, 4066, 3468]
      circular: false
  pods:
    n_pods: 57 # one per station per line | could be infered if n_pods == sum(len(line.stations))
people:
  n_people: 1
