- city: München
  id: 0
  lat: 11.5654
  lon: 48.1394
  name: Karlsplatz (Stachus)
- city: München
  id: 1
  lat: 11.5777
  lon: 48.1364
  name: Marienplatz
- city: München
  id: 2
  lat: 11.5828
  lon: 48.1339
  name: Isartor
- city: München
  id: 4
  lat: 11.6041
  lon: 48.1281
  name: Ostbahnhof
- city: München
  id: 5
  lat: 11.5611
  lon: 48.1403
  name: Hauptbahnhof
- city: München
  id: 6
  lat: 11.5488
  lon: 48.1435
  name: Hackerbrücke
- city: München
  id: 9
  lat: 11.4606
  lon: 48.1488
  name: Pasing
- city: München
  id: 10
  lat: 11.5474
  lon: 48.1595
  name: Leonrodplatz
- city: München
  id: 17
  lat: 11.5881
  lon: 48.1376
  name: Maxmonument
- city: München
  id: 19
  lat: 11.5753
  lon: 48.1395
  name: Theatinerstraße
- city: München
  id: 20
  lat: 11.596
  lon: 48.1361
  name: Maximilianeum
- city: München
  id: 27
  lat: 11.5496
  lon: 48.1251
  name: Poccistraße
- city: München
  id: 29
  lat: 11.5533
  lon: 48.1554
  name: Hochschule München
- city: München
  id: 34
  lat: 11.5584
  lon: 48.1295
  name: Goetheplatz
- city: München
  id: 37
  lat: 11.575
  lon: 48.1603
  name: Kurfürstenplatz
- city: München
  id: 44
  lat: 11.5664
  lon: 48.1333
  name: Sendlinger Tor
- city: München
  id: 46
  lat: 11.5696
  lon: 48.1454
  name: Karolinenplatz
- city: München
  id: 48
  lat: 11.5359
  lon: 48.1463
  name: Donnersbergerstraße
- city: München
  id: 54
  lat: 11.5777
  lon: 48.1429
  name: Odeonsplatz
- city: München
  id: 59
  lat: 11.5344
  lon: 48.14
  name: Trappentreustraße
- city: München
  id: 64
  lat: 11.5805
  lon: 48.149
  name: Universität
- city: München
  id: 74
  lat: 11.5849
  lon: 48.1571
  name: Giselastraße
- city: München
  id: 101
  lat: 11.564
  lon: 48.1462
  name: Königsplatz
- city: München
  id: 111
  lat: 11.5643
  lon: 48.1512
  name: Theresienstraße
- city: München
  id: 121
  lat: 11.5663
  lon: 48.1548
  name: Josephsplatz
- city: München
  id: 131
  lat: 11.568
  lon: 48.1612
  name: Hohenzollernplatz
- city: München
  id: 138
  lat: 11.5762
  lon: 48.1279
  name: Fraunhoferstraße
- city: München
  id: 146
  lat: 11.5765
  lon: 48.1191
  name: Kolumbusplatz
- city: München
  id: 153
  lat: 11.5588
  lon: 48.1471
  name: Stiglmaierplatz
- city: München
  id: 154
  lat: 11.5446
  lon: 48.1503
  name: Maillingerstraße
- city: München
  id: 156
  lat: 11.5335
  lon: 48.153
  name: Rotkreuzplatz
- city: München
  id: 158
  lat: 11.5284
  lon: 48.1693
  name: Westfriedhof
- city: München
  id: 167
  lat: 11.4932
  lon: 48.1656
  name: Amalienburgstraße
- city: München
  id: 172
  lat: 11.5116
  lon: 48.1556
  name: Romanplatz
- city: München
  id: 197
  lat: 11.5522
  lon: 48.1357
  name: Theresienwiese
- city: München
  id: 198
  lat: 11.5397
  lon: 48.1335
  name: Schwanthalerhöhe
- city: München
  id: 200
  lat: 11.5227
  lon: 48.1344
  name: Westendstraße
- city: München
  id: 202
  lat: 11.503
  lon: 48.1355
  name: Laimer Platz
- city: München
  id: 212
  lat: 11.5074
  lon: 48.1804
  name: Moosach
- city: München
  id: 225
  lat: 11.5291
  lon: 48.1764
  name: Georg-Brauchle-Ring
- city: München
  id: 231
  lat: 11.5403
  lon: 48.2139
  name: Feldmoching
- city: München
  id: 249
  lat: 11.5666
  lon: 48.1755
  name: Petuelring
- city: München
  id: 258
  lat: 11.5567
  lon: 48.1787
  name: Olympiazentrum
- city: München
  id: 268
  lat: 11.5295
  lon: 48.182
  name: Olympia-Einkaufszentrum
- city: München
  id: 287
  lat: 11.5727
  lon: 48.1715
  name: Scheidplatz
- city: Garching (b München)
  id: 347
  lat: 11.6712
  lon: 48.2649
  name: Garching-Forschungszentrum
- city: München
  id: 354
  lat: 11.5863
  lon: 48.1619
  name: Münchner Freiheit
- city: München
  id: 357
  lat: 11.5912
  lon: 48.1875
  name: Schwabing Nord
- city: München
  id: 384
  lat: 11.5979
  lon: 48.1357
  name: Max-Weber-Platz
- city: München
  id: 386
  lat: 11.5886
  lon: 48.1396
  name: Lehel
- city: München
  id: 388
  lat: 11.6305
  lon: 48.176
  name: St. Emmeram
- city: München
  id: 434
  lat: 11.6136
  lon: 48.1522
  name: Effnerplatz
- city: München
  id: 439
  lat: 11.6232
  lon: 48.1537
  name: Arabellapark/Klinikum Bogenhausen
- city: München
  id: 444
  lat: 11.6204
  lon: 48.1533
  name: Arabellapark
- city: München
  id: 519
  lat: 11.6421
  lon: 48.1218
  name: St.-Veit-Straße
- city: München
  id: 523
  lat: 11.6337
  lon: 48.1361
  name: Berg am Laim
- city: München
  id: 593
  lat: 11.529
  lon: 48.1635
  name: Gern
- city: München
  id: 611
  lat: 11.6444
  lon: 48.0895
  name: Neuperlach Süd
- city: München
  id: 631
  lat: 11.6474
  lon: 48.101
  name: Neuperlach Zentrum
- city: München
  id: 641
  lat: 11.6464
  lon: 48.1091
  name: Quiddestraße
- city: München
  id: 650
  lat: 11.6306
  lon: 48.1188
  name: Michaelibad
- city: München
  id: 658
  lat: 11.6191
  lon: 48.1204
  name: Innsbrucker Ring
- city: München
  id: 662
  lat: 11.6095
  lon: 48.1185
  name: Karl-Preis-Platz
- city: München
  id: 668
  lat: 11.5836
  lon: 48.1191
  name: Ostfriedhof
- city: München
  id: 672
  lat: 11.5971
  lon: 48.1029
  name: Schwanseestraße
- city: München
  id: 673
  lat: 11.5946
  lon: 48.1108
  name: Giesing
- city: München
  id: 695
  lat: 11.5483
  lon: 48.1193
  name: Implerstraße
- city: München
  id: 704
  lat: 11.5335
  lon: 48.1334
  name: Heimeranplatz
- city: München
  id: 712
  lat: 11.5871
  lon: 48.1128
  name: Untersbergstraße
- city: München
  id: 722
  lat: 11.5795
  lon: 48.1152
  name: Silberhornstraße
- city: München
  id: 740
  lat: 11.5747
  lon: 48.1092
  name: Wettersteinplatz
- city: München
  id: 744
  lat: 11.5184
  lon: 48.1401
  name: Lautensackstraße
- city: München
  id: 750
  lat: 11.581
  lon: 48.0979
  name: Mangfallplatz
- city: München
  id: 763
  lat: 11.6447
  lon: 48.1259
  name: Kreillerstraße
- city: München
  id: 770
  lat: 11.7036
  lon: 48.1334
  name: Messestadt Ost
- city: München
  id: 875
  lat: 11.4804
  lon: 48.0886
  name: Fürstenried West
- city: München
  id: 895
  lat: 11.4738
  lon: 48.1089
  name: Klinikum Großhadern
- city: München
  id: 903
  lat: 11.49
  lon: 48.1246
  name: Gondrellplatz
- city: München
  id: 908
  lat: 11.5031
  lon: 48.1397
  name: Fürstenrieder Straße
- city: München
  id: 911
  lat: 11.4888
  lon: 48.1409
  name: Willibaldplatz
- city: Grünwald (Kr München)
  id: 1153
  lat: 11.5236
  lon: 48.0416
  name: Derbolfinger Platz
