# s1
- city: BenjaminTown
  id: 11
  lat: 0.5
  lon: 5.0
  name: NoName
  entrypoint_for: ["s1+", "s2+"]
- city: BenjaminTown
  id: 12
  lat: 1.5
  lon: 5.0
  name: NoName
- city: BenjaminTown
  id: 13
  lat: 3.0
  lon: 5.0
  name: NoName
- city: BenjaminTown
  id: 14
  lat: 4.0
  lon: 5.0
  name: NoName
- city: BenjaminTown
  id: 15
  lat: 5.8
  lon: 5.0
  name: NoName
# id: 5
- city: BenjaminTown
  id: 16
  lat: 6.5
  lon: 5.0
  name: NoName
- city: BenjaminTown
  id: 17
  lat: 7.5
  lon: 5.0
  name: NoName
- city: BenjaminTown
  id: 18
  lat: 9.0
  lon: 5.0
  name: NoName
- city: BenjaminTown
  id: 19
  lat: 11.0
  lon: 5.0
  name: NoName
  entrypoint_for: ["s1-"]

# s2
# id: 11
# id: 12
# id: 13
# id: 14
# id: 5
# id: 15
# id: 16
# id: 17
- city: BenjaminTown
  id: 53
  lat: 8.5
  lon: 3.5
  name: NoName
- city: BenjaminTown
  id: 52
  lat: 10.0
  lon: 3.0
  name: NoName
- city: BenjaminTown
  id: 51
  lat: 11.0
  lon: 3.0
  name: NoName
  entrypoint_for: ["s2-"]

# u1
- city: BenjaminTown
  id: 1
  lat: 1.0
  lon: 1.0
  name: NoName
  entrypoint_for: ["u1+"]
- city: BenjaminTown
  id: 2
  lat: 2.0
  lon: 2.0
  name: NoName
- city: BenjaminTown
  id: 3
  lat: 3.0
  lon: 3.0
  name: NoName
- city: BenjaminTown
  id: 4
  lat: 4.3
  lon: 3.8
  name: NoName
- city: BenjaminTown
  id: 5
  lat: 5.0
  lon: 5.0
  name: NoName
- city: BenjaminTown
  id: 6
  lat: 6.0
  lon: 6.0
  name: NoName
- city: BenjaminTown
  id: 7
  lat: 6.5
  lon: 6.5
  name: NoName
- city: BenjaminTown
  id: 8
  lat: 8.0
  lon: 8.0
  name: NoName
- city: BenjaminTown
  id: 9
  lat: 9.5
  lon: 9.0
  name: NoName
- city: BenjaminTown
  id: 10
  lat: 11.0
  lon: 9.5
  name: NoName
  entrypoint_for: ["u1-"]

# u2
- city: BenjaminTown
  id: 21
  lat: 5.5
  lon: 0.5
  name: NoName
  entrypoint_for: ["u2+", "u3+"]
- city: BenjaminTown
  id: 22
  lat: 5.5
  lon: 1.5
  name: NoName
- city: BenjaminTown
  id: 23
  lat: 4.5
  lon: 2.5
  name: NoName
# id: 4
# id: 5
- city: BenjaminTown
  id: 24
  lat: 4.5
  lon: 6.0
  name: NoName
- city: BenjaminTown
  id: 25
  lat: 3.5
  lon: 7.0
  name: NoName
- city: BenjaminTown
  id: 26
  lat: 2.5
  lon: 8.0
  name: NoName
- city: BenjaminTown
  id: 27
  lat: 1.5
  lon: 9.0
  name: NoName
- city: BenjaminTown
  id: 28
  lat: 0.5
  lon: 9.5
  name: NoName
  entrypoint_for: ["u2-", "u3-", "u4-"]

# u3
# id: 21
# id: 22
- city: BenjaminTown
  id: 31
  lat: 6.0
  lon: 2.5
  name: NoName
- city: BenjaminTown
  id: 32
  lat: 6.5
  lon: 3.5
  name: NoName
# id: 15
# id: 6
- city: BenjaminTown
  id: 33
  lat: 6.0
  lon: 8.0
  name: NoName
- city: BenjaminTown
  id: 34
  lat: 4.5
  lon: 8.5
  name: NoName
- city: BenjaminTown
  id: 35
  lat: 3.5
  lon: 8.5
  name: NoName
# id: 27
# id: 28

# u4
- city: BenjaminTown
  id: 41
  lat: 10.0
  lon: 0.5
  name: NoName
  entrypoint_for: ["u4+"]
- city: BenjaminTown
  id: 42
  lat: 9.0
  lon: 1.5
  name: NoName
- city: BenjaminTown
  id: 43
  lat: 8.5
  lon: 2.5
  name: NoName
- city: BenjaminTown
  id: 44
  lat: 7.5
  lon: 3.0
  name: NoName
# id: 32
- city: BenjaminTown
  id: 45
  lat: 5.5
  lon: 4.0
  name: NoName
# id: 5
# id: 24
# id: 25
# id: 26
# id: 27
# id: 28

# u5
- city: BenjaminTown
  id: 61
  lat: 3.0
  lon: 0.5
  name: NoName
  entrypoint_for: ["u5+"]
- city: BenjaminTown
  id: 62
  lat: 3.5
  lon: 1.5
  name: NoName
# id: 23
- city: BenjaminTown
  id: 63
  lat: 5.1
  lon: 3.2
  name: NoName
# id: 45
# id: 15
# id: 6
# id: 33
- city: BenjaminTown
  id: 64
  lat: 7.0
  lon: 9.5
  name: NoName
- city: BenjaminTown
  id: 65
  lat: 8.0
  lon: 10.0
  name: NoName
- city: BenjaminTown
  id: 66
  lat: 9.5
  lon: 10.5
  name: NoName
  entrypoint_for: ["u5-"]

# t11 -> Ringline
- city: BenjaminTown
  id: 71
  lat: 5.3
  lon: 6.2
  name: NoName
  entrypoint_for: ["t11+-"]
# id: 6
# id: 15
# id: 32
# id: 31
# id: 22
# id: 23
# id: 4
# id: 14
# id: 24

# t12 -> Ringline
- city: BenjaminTown
  id: 81
  lat: 7.5
  lon: 1.0
  name: NoName
  entrypoint_for: ["t12+-"]
# id: 21
# id: 62
# id: 3
# id: 13
# id: 25
# id: 34
# id: 33
# id: 8
# id: 18
# id: 53
# id: 43